const state=JSON.parse(localStorage.getItem('breakwaterState')||'{"solved":{},"hints":{},"notes":{},"alias":""}');
state.notes=state.notes||{}; state.alias=state.alias||'';
const save=()=>localStorage.setItem('breakwaterState',JSON.stringify(state));
async function sha256(s){const b=new TextEncoder().encode(s.trim().toUpperCase());const h=await crypto.subtle.digest('SHA-256',b);return [...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,'0')).join('');}
let challenges=[];
async function init(){challenges=await (await fetch('data/challenges.json')).json();const a=document.querySelector('#alias');if(a)a.value=state.alias;render();}
function saveAlias(v){state.alias=v.trim();save();}
function saveNote(id,v){state.notes[id]=v;save();}
function hintPenalty(c){return (state.hints[c.id]||0)*10}
function earned(c){return state.solved[c.id]?Math.max(0,c.points-hintPenalty(c)):0}
function totals(){return {score:challenges.reduce((a,c)=>a+earned(c),0),max:challenges.reduce((a,c)=>a+c.points,0),done:Object.keys(state.solved).filter(k=>state.solved[k]).length}}
function capabilityData(){const skills={};challenges.forEach(c=>c.skills.forEach(s=>{skills[s]??={got:0,max:0};skills[s].max+=c.points/c.skills.length;if(state.solved[c.id])skills[s].got+=earned(c)/c.skills.length;}));return Object.fromEntries(Object.entries(skills).map(([s,v])=>[s,v.max?Math.round(v.got/v.max*100):0]));}
function render(){const g=document.querySelector('#grid');g.innerHTML='';challenges.forEach(c=>{const el=document.createElement('section');el.className='card '+(state.solved[c.id]?'done':'');const note=(state.notes[c.id]||'').replace(/</g,'&lt;').replace(/>/g,'&gt;');el.innerHTML=`<div class="meta"><span class="pill">#${String(c.id).padStart(2,'0')}</span><span class="pill">${c.track}</span><span class="pill">${c.difficulty}</span><span class="pill">${c.points} pts</span></div><h3>${c.title}</h3><p class="desc">${c.desc}</p><div class="artifact"><a class="btn" href="${c.artifact}" target="_blank">Open bronbestand</a></div><div class="small">Skills: ${c.skills.join(' · ')}</div><label class="notelabel" for="n${c.id}">Analyst log <span>observable → pivot → corroboration → flag</span></label><textarea id="n${c.id}" class="notes" placeholder="Noteer kort wat je zag, welke pivot je maakte en hoe je verifieerde." oninput="saveNote(${c.id},this.value)">${note}</textarea><div class="flagrow"><input id="f${c.id}" placeholder="CTF{...}" ${state.solved[c.id]?'disabled':''}><button onclick="submitFlag(${c.id})" ${state.solved[c.id]?'disabled':''}>Submit</button></div><div id="m${c.id}" class="msg">${state.solved[c.id]?'<span class="ok">✓ Correct</span>':''}</div><div><button onclick="showHint(${c.id})">Hint (${10} pt)</button></div><div id="h${c.id}"></div>`;g.appendChild(el); if((state.hints[c.id]||0)>0) renderHints(c);});updateStats();renderMatrix();}
async function submitFlag(id){const c=challenges.find(x=>x.id===id);const v=document.querySelector('#f'+id).value;const hh=await sha256(v);const m=document.querySelector('#m'+id);if(hh===c.flag_hash){state.solved[id]=true;save();m.innerHTML='<span class="ok">✓ Correct. Flag accepted.</span>';render();}else m.innerHTML='<span class="bad">✗ Niet correct. Controleer format en redenering.</span>';}
function showHint(id){const c=challenges.find(x=>x.id===id);const n=state.hints[id]||0;if(n>=c.hints.length)return;state.hints[id]=n+1;save();renderHints(c);updateStats();renderMatrix();}
function renderHints(c){const n=state.hints[c.id]||0;document.querySelector('#h'+c.id).innerHTML=c.hints.slice(0,n).map((x,i)=>`<div class="hintbox"><b>Hint ${i+1}</b> · −10 pt<br>${x}</div>`).join('');}
function updateStats(){const t=totals();document.querySelector('#score').textContent=t.score;document.querySelector('#max').textContent=t.max;document.querySelector('#done').textContent=`${t.done}/${challenges.length}`;document.querySelector('#pct').textContent=Math.round((t.score/t.max)*100)+'%';}
function renderMatrix(){const skills=capabilityData();const box=document.querySelector('#matrix');box.innerHTML='<h3>Persoonlijke capability matrix</h3><p class="small">Gebaseerd op behaalde punten per skill. Hints verlagen de score.</p>'+Object.entries(skills).map(([s,p])=>`<div class="row"><span>${s}</span><div class="bar"><i style="width:${p}%"></i></div><b>${p}%</b></div>`).join('');}
function safeName(){return (state.alias||'deelnemer').replace(/[^a-z0-9_-]+/gi,'_').replace(/^_+|_+$/g,'').slice(0,40)||'deelnemer';}
function resultObject(){const t=totals();return {ctf:'Operation BREAKWATER',version:'1.1',exported_at:new Date().toISOString(),participant:state.alias||'',score:t.score,max_score:t.max,solved_count:t.done,total_challenges:challenges.length,capability_matrix:capabilityData(),challenges:challenges.map(c=>({id:c.id,title:c.title,track:c.track,difficulty:c.difficulty,points:c.points,earned_points:earned(c),solved:!!state.solved[c.id],hints_used:state.hints[c.id]||0,skills:c.skills,analyst_log:state.notes[c.id]||''}))};}
function downloadBlob(content,type,filename){const blob=new Blob([content],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);document.querySelector('#exportmsg').textContent=`Resultaatbestand aangemaakt: ${filename}. Stuur dit bestand naar de organisator.`;}
function exportJSON(){const r=resultObject();downloadBlob(JSON.stringify(r,null,2),'application/json',`BREAKWATER_${safeName()}_resultaat.json`);}
function csvEsc(v){v=v==null?'':String(v);return /[",\n]/.test(v)?'"'+v.replace(/"/g,'""')+'"':v;}
function exportCSV(){const r=resultObject();const rows=[['ctf','participant','exported_at','challenge_id','title','track','difficulty','solved','hints_used','earned_points','max_points','skills','analyst_log']];r.challenges.forEach(c=>rows.push([r.ctf,r.participant,r.exported_at,c.id,c.title,c.track,c.difficulty,c.solved,c.hints_used,c.earned_points,c.points,c.skills.join('|'),c.analyst_log]));rows.push([]);rows.push(['SUMMARY','participant',r.participant,'score',r.score,'max_score',r.max_score,'solved',r.solved_count,'total',r.total_challenges]);Object.entries(r.capability_matrix).forEach(([k,v])=>rows.push(['CAPABILITY',k,v+'%']));downloadBlob(rows.map(row=>row.map(csvEsc).join(',')).join('\n'),'text/csv;charset=utf-8',`BREAKWATER_${safeName()}_resultaat.csv`);}
function resetAll(){if(confirm('Alle lokale voortgang wissen?')){localStorage.removeItem('breakwaterState');location.reload();}}
init();